### ISSUE TITLE
UB in C11

### ISSUE THREAD

**Issue by orilahav** [bittnkr/uniq#5]
From a formal standpoint, this implementation seems broken since you have date races on buffer[...], and C/C++11 says this is UB.

**Comment by bittnkr** [comment]
Hello dear,
Thanks for your comment. 
Could you post some code to illustrate your viewpoint?

**Comment by orilahav** [comment]
Consider:

push(1) || pop // returns 1

In the push(1) you have a write to buffer[0]. In the pop you have a read from buffer[0]. There is no C11's "happens before" relation between these accesses (to have it one needs to at least have an atomic access after the write to buffer[0] but there isn't one), and so there is a race here. Since buffer[0] is non-atomic, this means that the program has undefined behavior (UB). There is also a similar (earlier) race on isFree[0].

Am I missing something?

**Comment by bittnkr** [comment]
Maybe I am missing your point.

Could you clarify your observations with a couple of lines of code?
If you could produce a race condition using only push() and pop() would be splendid.

**Comment by X-Ryl669** [comment]
I haven't read the code, but I can comment on the OP's concern here, you've put in your example implementation this:

Let's say thread A runs `push(1)` and is scheduled where I've added the SCHEDULE comment
```cpp
push(item) 
{
  let i
  do {
    i = in // get a local copy the next id

    while (i - out == size) sleep() // if full, wait for space
  
  } while ( (data[i & mask]) || (CompareAndSwap(in, i+1, i) != i) )
  // if the seat is lost or CAS failed, try again. 
  ////////// SCHEDULE HERE: A
  data[i & mask] = item // now is safe to update the buffer using local i
  return i // id of the job 
}
```
And simultaneously, thread B then runs:
```
pop() 
{
  let o
  do {
    o = out // id of the next candidate

    while (o == in) sleep() // if empty, wait for items

  } while ( !(data[o & mask]) || CompareAndSwap(out, o+1, o) != o )
  // if the candidate is gone or CAS failed, try again. 

  o &= mask // round to fit the buffer
  int r = data[o] // save the return ////////  HERE THE THREAD IS READING BULLSHIT
  buffer[o] = 0 // release the seat
  return r
}
```
While the position (o) or (i) are good for both thread, thread B will read random value since thread A hasn't written it yet. 
You must perform your CAS only after the write is done and if it's not done, you must revert what you did. 

That's the reason why it's not possible to make a circular buffer lockfree queue: you need to write 2 values at 2 different locations atomically. 
That's also the reason why you need to check for `data[o & mask]` not to be 0 in your loop, you added a check on the value in the queue because else, you'd have observed the behavior I'm describing.
 
Said differently, if you try to push 0 in the queue, it'll never work correctly.

**Comment by X-Ryl669** [comment]
BTW, `data[o & mask]` or `isFree[o & mask]` works as a lock. (TBH, it's a spin lock). So this code isn't lock free, nor wait free.

**Comment by bittnkr** [comment]
@X-Ryl669, @orilahav 

Thanks for your considerations.

` int r = data[o] // save the return ////////  HERE THE THREAD IS READING BULLSHIT`

Sorry, but this is not true. On that point the buffer seat is already reserved by the successful CAS() , and its impossible to another thread get that position simply using `push()` and `pop()`. Even if the buffer take a full buffer cycle.  Because the way the atomic guardians `in` and `out` are updated.

Pay attention to the fact that the last thing pop() does its to mark the seat as free, through `buffer[o & mask] = 0 or setting `isFree[o & mask] =0;` and the first thing the `push()` while loop do is to verify if the seat is empty before trying do the CAS(). 

There is no lock, neither a spinlock, despite de fact I'm using a while() loop. **Because we have a buffer.**  If the seat was taken by another thread, the failed thread just will go to another seat. 

There are just two situations where the code will wait or return false: If the buffer is empty or full. 

Otherwise It will flow without any lock. And even this is not a lock, is just a signal that the queue is empty and there is nothing more to do or it is full and need to wait another thread to remove an element from the buffer to get in.

Please stress the code. Could you get a checksum different from zero?

**Comment by bittnkr** [comment]
@X-Ryl669

Thanks for your considerations.

int r = data[o] // save the return //////// HERE THE THREAD IS READING BULLSHIT

This is not true. On that point the buffer seat is already reserved by the successful CAS() , and its impossible to another thread get that position simply using push(). Even if the buffer take a full cycle or a thread preemption. Because the way the atomic guardians in and out are updated. 

Pay attention to the fact that the last thing pop() does its to mark the seat as free, through isFree[o & mask] = true; and the first thing the push() do is to verify if the seat is empty before trying do the `CAS()`.

There is no lock, neither a spinlock like `while(!condition) {}`, despite the fact I'm using a while() loop. **Because we have a buffer**. If the seat was taken by another thread, the failed thread just will go to another seat. Without any lock. (I even wrote about this possibility in the docs.)

There are just two situations where the code will wait or return: If the buffer is empty or full. 

And even this is not a lock, is just a signal that the queue is empty and there is nothing more to do or it is full and then need to wait another thread to remove an element from the buffer before get in. (In this case you can tune it increasing the size of the buffer, or the number of consumers.) Otherwise It will flow naturally.

Please stress the code. Could you get a checksum different of zero, using push and pop?

**Comment by bittnkr** [comment]
@X-Ryl669

Thanks for your considerations.

`int r = data[o] // save the return //////// HERE THE THREAD IS READING BULLSHIT`

On that point the buffer seat is already reserved by the successful `CAS()` , and its impossible to another thread get that position just using `push()`. Even if the buffer take a full cycle or a thread preemption. Because the way the atomic guardians `in` and `out` are updated. 

Pay attention to the fact that the last thing `pop()` does its to mark the seat as free, through `isFree[o & mask] = true` and the first thing the `push()` do is to verify if the seat is empty before trying do the `CAS()`.

There is no lock, neither a spinlock like `while(condition) {}`, despite the fact I'm using a while() loop. **Because we have a buffer**. If the seat was taken by another thread, the failed thread just will go to another seat. Without any lock. (I even wrote about this possibility in the docs.)

There are just two situations where the code will wait or return: If the buffer is empty or full. 

And even this is not a lock, is just a signal that there is nothing more to do, or it is full and then need to wait another thread to remove an element from the buffer before get in. (In this case you can tune it increasing the size of the buffer, or the number of consumers.) Otherwise It will flow naturally.
